`Deadpool happy with his lively wife.`

SELECT `TABLE_NAME` 
FROM information_schema.columns 
WHERE column_name = 'Region';


ALTER TABLE `TABLE_NAME`
ADD PRIMARY KEY(`Region`);

ALTER TABLE `ARMM` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `CAR` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `CARAGA` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `NCR`ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `NIR` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `REG_I` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `REG_II` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `REG_III` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `REG_IV_A` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `REG_IV_B` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `REG_IX` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `REG_V` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `REG_VI` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `REG_VII` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `REG_VIII` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `REG_X` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `REG_XI` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);
ALTER TABLE `REG_XII` ADD FOREIGN KEY(`REGION`) REFERENCES REGIONS(`Region Number`);


article id add row
geotag
tourist spot

